<?php
/**
 * Status Checks - PHP Server/Network Status Monitor and Notifications
 * http://statuschecks.net
 * Author: Ben Townsend
 * Licensed Under: GNU GENERAL PUBLIC LICENSE V2
 * Date: 7/14/15
 * Time: 10:33 PM
 */

namespace StatusChecks;
?>

<div class="container">

    <div class="starter-template">
        <h1><?php echo Core::get('name'); ?></h1>
<p class="lead">Test Template - Based on Twitter Bootstrap</p>
</div>

</div><!-- /.container -->